#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Verbosity and settings that you pretty much just always are going to want.
alias	cp="cp -iv" 
alias	mv="mv -iv" 
#alias	rm="rm -vI" 
alias	mkd="mkdir -pv" 
alias	yt="youtube-dl --add-metadata -i" 
alias	yta="yt -x -f bestaudio/best" 
alias	ffmpeg="ffmpeg -hide_banner"
# confirm before overwriting something
#alias cp="cp -i"
#alias mv='mv -i'
#alias rm='rm -i'

# navigation
alias ..='cd ..'
alias ...='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'

# Colorize commands when possible.
# Changing "ls" to "exa"
alias	ls='exa -al --color=always --group-directories-first' 
alias	la='exa -a --color=always --group-directories-first'  
alias	ll='exa -l --color=always --group-directories-first'  
alias	lt='exa -aT --color=always --group-directories-first' 
alias	l.='exa -a | egrep "^\."'

# Colorize grep output (good for log files)
alias grep='grep --color=auto' 
alias egrep='egrep --color=auto' 
alias fgrep='fgrep --color=auto' 

	 # broot
alias br='broot -dhp'
alias bs='broot --sizes'

# pacman and yay
alias	p="sudo pacman" 
alias pacsyu='sudo pacman -Syyu'                 # update only standard pkgs
alias	psua="paru -Sua --noconfirm"  
alias	psyu="paru -Syu --noconfirm"  
alias xi="sudo xbps-install" 
alias	xr="sudo xbps-remove -R" 
alias xq="xbps-query" 
alias unlock='sudo rm /var/lib/pacman/db.lck'    # remove pacman lock
alias cleanup='sudo pacman -Rns (pacman -Qtdq)'  # remove orphaned packages

	# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
alias	mirrorc="sudo reflector -c Germany -c France -a 12 -p https -p http --sort rate --save /etc/pacman.d/mirrorlist"  

# These common commands are just too long! Abbreviate them.
alias	ka="killall" 
alias	g="git" 
alias	trem="transmission-remote" 
alias	YT="youtube-viewer" 
alias	sdn="sudo shutdown -h now" 
alias	f="$FILE" 
alias	e="$EDITOR" 
alias	v="$EDITOR" 
alias	z="zathura"

alias	magit="nvim -c MagitOnly" 
alias	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/zshnameddirrc" 
alias	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" 
alias	tmux="tmux -f ${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf" 

# adding flags
alias	df='df -h'  
alias free='free -m'  
   	                  
# switch between shells
alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"  
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"  
alias tofish="sudo chsh $USER -s /bin/fish && echo 'Now log out.'"  

## get top process eating memory
alias	psmem='ps auxf | sort -nr -k 4'  
alias	psmem10='ps auxf | sort -nr -k 4 | head -10'  

## get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3'  
alias	pscpu10='ps auxf | sort -nr -k 3 | head -10'  

# get error messages from journalctl
alias jctl="journalctl -p 3 -xb"

# gpg encryption
# verify signature for isos
alias gpg-check="gpg2 --keyserver-options auto-key-retrieve --verify"
# receive the key of a developer
alias gpg-retrieve="gpg2 --keyserver-options auto-key-retrieve --receive-keys"

# youtube-dl
#alias yta-aac="youtube-dl --extract-audio --audio-format aac "
#alias yta-best="youtube-dl --extract-audio --audio-format best "
#alias yta-flac="youtube-dl --extract-audio --audio-format flac "
#alias yta-m4a="youtube-dl --extract-audio --audio-format m4a "
#alias yta-mp3="youtube-dl --extract-audio --audio-format mp3 "
#alias yta-opus="youtube-dl --extract-audio --audio-format opus "
#alias yta-vorbis="youtube-dl --extract-audio --audio-format vorbis "
#alias yta-wav="youtube-dl --extract-audio --audio-format wav "
#alias ytv-best="youtube-dl -f bestvideo+bestaudio "

# git
#alias clone='git clone'

# termbin
alias tb="nc termbin.com 9999"


